services:
  sweet-manager.api:
    image: ryzeon/sweet-manager.api:latest
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: sweetmanager.API/Dockerfile
    environment:
      SweetManagerDbConnection: Server=sweet-manager_mysql;Database=sweetmanager;User=root;Password=securepassword123
    restart: always
    depends_on:
      sweet-manager_mysql:
        condition: service_healthy
  sweet-manager_mysql:
    image: 'mysql:latest'
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: securepassword123
      MYSQL_PASSWORD: securepassword123
      MYSQL_DATABASE: sweetmanager
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10